"""baseline schema

Revision ID: 5bd98fadc19f
Revises: 
Create Date: 2026-07-04 08:01:19.157805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '5bd98fadc19f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Areas'))
    )
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Categories'))
    )
    op.create_table('Locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Locations'))
    )
    op.create_table('Sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Sessions'))
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users')),
    sa.UniqueConstraint('username', name=op.f('uq_Users_username'))
    )
    op.create_table('Homes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['Users.id'], name=op.f('fk_Homes_created_by_Users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Homes'))
    )
    op.create_table('Items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], name=op.f('fk_Items_category_id_Categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Items'))
    )
    op.create_table('HomeMembers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['Homes.id'], name=op.f('fk_HomeMembers_home_id_Homes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_HomeMembers_user_id_Users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_HomeMembers')),
    sa.UniqueConstraint('home_id', 'user_id', name='uq_home_member')
    )
    op.create_table('Lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdBy', sa.String(length=255), nullable=False),
    sa.Column('collaborators', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['Homes.id'], name=op.f('fk_Lists_home_id_Homes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Lists'))
    )
    op.create_table('ListItems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('checked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('createdAt', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updatedAt', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['Areas.id'], name=op.f('fk_ListItems_area_id_Areas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], name=op.f('fk_ListItems_category_id_Categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['Items.id'], name=op.f('fk_ListItems_item_id_Items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['Lists.id'], name=op.f('fk_ListItems_list_id_Lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ListItems'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ListItems')
    op.drop_table('Lists')
    op.drop_table('HomeMembers')
    op.drop_table('Items')
    op.drop_table('Homes')
    op.drop_table('Users')
    op.drop_table('Sessions')
    op.drop_table('Locations')
    op.drop_table('Categories')
    op.drop_table('Areas')
    # ### end Alembic commands ###
